version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8082
      - WEB_PORT=8083
      - DB_PORT=5435
      - MATTER_BRIDGE_PORT=8085
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=msh;Username=postgres;Password=postgres;
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "${WEB_PORT:-8083}:8082"
    volumes:
      - msh_dataprotection:/root/.aspnet/DataProtection-Keys
    networks:
      - msh-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=msh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth-host=md5 --auth-local=md5
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d msh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "${DB_PORT:-5435}:5432"
    volumes:
      - msh_postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - msh-network

  matter-bridge:
    build:
      context: ./Matter
      dockerfile: Dockerfile.simple
    environment:
      - MATTER_BRIDGE_HOST=0.0.0.0
      - MATTER_BRIDGE_PORT=8084
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "${MATTER_BRIDGE_PORT:-8085}:8084"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/vhci:/dev/vhci
      - /dev/bus/usb:/dev/bus/usb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    networks:
      - msh-network
    depends_on:
      - web

networks:
  msh-network:
    driver: bridge

volumes:
  msh_postgres_data:
    driver: local
  msh_dataprotection:
    driver: local 