version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword  # Match your appsettings.Development.json
      POSTGRES_DB: matter_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: src/MSH.Web/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Development: "Host=db;Port=5432;Database=matter_dev;Username=postgres;Password=devpassword"

volumes:
  postgres-data:
