version: '3.8'

services:
  app:
    build: .
    ports: ["8080:8080"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION: "Host=db;Database=matter_dev;Username=postgres;Password=devpassword"

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: devpassword
