version: '3.8'

services:
  otbr:
    image: openthread/otbr:latest
    container_name: otbr-border-router
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      # Nordic nRF52840 dongle for Thread
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      # Persistent storage for Thread network data
      - otbr_data:/var/lib/thread
      # Network configuration
      - /etc/networks:/etc/networks:ro
      - /etc/hosts:/etc/hosts:ro
    environment:
      # Thread network configuration
      - OTBR_INFRA_IF_NAME=wlan0
      - OTBR_DBUS=ON
      - OTBR_WEB=ON
      - OTBR_REST=ON
      - OTBR_FIREWALL=OFF
      # Network settings for Pi (IP ending with 107)
      - OTBR_BACKBONE_ROUTER=ON
      - OTBR_NAT64=OFF
      # Port configuration for host network mode
      - OTBR_WEB_PORT=9999
      - OTBR_REST_PORT=8081
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

volumes:
  otbr_data:
    driver: local 