--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Debian 16.8-1.pgdg120+1)
-- Dumped by pg_dump version 16.8 (Debian 16.8-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ApplicationUsers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ApplicationUsers" (
    "Id" text NOT NULL,
    "UserName" text NOT NULL,
    "Email" text,
    "FirstName" text,
    "LastName" text,
    "IsActive" boolean NOT NULL,
    "LastLogin" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


--
-- Name: Clusters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Clusters" (
    "Id" uuid NOT NULL,
    "ClusterId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Category" character varying(50),
    "IsRequired" boolean DEFAULT false NOT NULL,
    "IsOptional" boolean DEFAULT true NOT NULL,
    "MatterVersion" character varying(20),
    "Attributes" jsonb,
    "Commands" jsonb,
    "Events" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean DEFAULT false NOT NULL,
    "CreatedById" character varying(500) NOT NULL,
    "UpdatedById" character varying(500)
);


--
-- Name: DeviceDeviceGroup; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DeviceDeviceGroup" (
    "DeviceGroupsId" uuid NOT NULL,
    "DevicesId" uuid NOT NULL
);


--
-- Name: DeviceEvents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DeviceEvents" (
    "Id" uuid NOT NULL,
    "DeviceId" uuid NOT NULL,
    "EventType" text NOT NULL,
    "EventData" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: DeviceFirmwareUpdates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DeviceFirmwareUpdates" (
    "Id" uuid NOT NULL,
    "DeviceId" uuid NOT NULL,
    "FirmwareUpdateId" uuid NOT NULL,
    "CurrentVersion" character varying(50) NOT NULL,
    "TargetVersion" character varying(50) NOT NULL,
    "Status" character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    "DownloadStartedAt" timestamp with time zone,
    "DownloadCompletedAt" timestamp with time zone,
    "InstallationStartedAt" timestamp with time zone,
    "InstallationCompletedAt" timestamp with time zone,
    "TestCompletedAt" timestamp with time zone,
    "TestPassed" boolean DEFAULT false NOT NULL,
    "ErrorMessage" character varying(500),
    "TestResults" jsonb,
    "IsConfirmed" boolean DEFAULT false NOT NULL,
    "ConfirmedAt" timestamp with time zone,
    "ConfirmedBy" character varying(50),
    "IsRollbackAvailable" boolean DEFAULT false NOT NULL,
    "RollbackCompletedAt" timestamp with time zone,
    "RollbackReason" character varying(500),
    "UpdateLog" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean DEFAULT false NOT NULL,
    "CreatedById" character varying(500) NOT NULL,
    "UpdatedById" character varying(500)
);


--
-- Name: DeviceGroupMembers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DeviceGroupMembers" (
    "DeviceId" uuid NOT NULL,
    "DeviceGroupId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text,
    "Comment" text
);


--
-- Name: DeviceGroups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DeviceGroups" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "RoomId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text,
    "DefaultCapabilities" jsonb,
    "Icon" text DEFAULT 'oi-device-hdd'::text,
    "PreferredCommissioningMethod" text DEFAULT 'BLE_WiFi'::text,
    "SortOrder" integer DEFAULT 0,
    "IsActive" boolean DEFAULT true
);


--
-- Name: DeviceHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DeviceHistory" (
    "Id" uuid NOT NULL,
    "DeviceId" uuid NOT NULL,
    "EventType" text NOT NULL,
    "OldState" jsonb,
    "NewState" jsonb,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: DevicePropertyChanges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DevicePropertyChanges" (
    "Id" uuid NOT NULL,
    "DeviceId" uuid NOT NULL,
    "PropertyName" character varying(100) NOT NULL,
    "OldValue" jsonb,
    "NewValue" jsonb,
    "ChangeType" character varying(50) DEFAULT 'update'::character varying NOT NULL,
    "Reason" character varying(200),
    "ChangeTimestamp" timestamp with time zone NOT NULL,
    "IsConfirmed" boolean DEFAULT false NOT NULL,
    "ConfirmedAt" timestamp with time zone,
    "ConfirmedBy" character varying(50),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean DEFAULT false NOT NULL,
    "CreatedById" character varying(500) NOT NULL,
    "UpdatedById" character varying(500)
);


--
-- Name: DeviceStates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DeviceStates" (
    "Id" uuid NOT NULL,
    "DeviceId" uuid NOT NULL,
    "StateType" text NOT NULL,
    "StateValue" jsonb NOT NULL,
    "RecordedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: DeviceTypes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."DeviceTypes" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Capabilities" jsonb NOT NULL,
    "IsSimulated" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text,
    "DeviceGroupId" uuid,
    "Icon" text,
    "PreferredCommissioningMethod" text
);


--
-- Name: Devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Devices" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "MatterDeviceId" text,
    "DeviceTypeId" uuid NOT NULL,
    "RoomId" uuid,
    "Properties" jsonb NOT NULL,
    "Status" text NOT NULL,
    "Configuration" jsonb,
    "LastStateChange" timestamp with time zone NOT NULL,
    "IsOnline" boolean NOT NULL,
    "LastSeen" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: EnvironmentalSettings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."EnvironmentalSettings" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "IndoorTemperatureMin" double precision NOT NULL,
    "IndoorTemperatureMax" double precision NOT NULL,
    "OutdoorTemperatureMin" double precision NOT NULL,
    "OutdoorTemperatureMax" double precision NOT NULL,
    "HumidityMin" double precision NOT NULL,
    "HumidityMax" double precision NOT NULL,
    "CO2Max" double precision NOT NULL,
    "VOCMax" double precision NOT NULL,
    "TemperatureWarning" double precision NOT NULL,
    "HumidityWarning" double precision NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: FirmwareUpdates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."FirmwareUpdates" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "CurrentVersion" character varying(50) NOT NULL,
    "TargetVersion" character varying(50) NOT NULL,
    "DownloadUrl" character varying(200),
    "FileName" character varying(100),
    "FileSize" bigint,
    "Checksum" character varying(100),
    "Status" character varying(20) DEFAULT 'available'::character varying NOT NULL,
    "DownloadStartedAt" timestamp with time zone,
    "DownloadCompletedAt" timestamp with time zone,
    "InstallationStartedAt" timestamp with time zone,
    "InstallationCompletedAt" timestamp with time zone,
    "ErrorMessage" character varying(500),
    "UpdateMetadata" jsonb,
    "IsCompatible" boolean DEFAULT true NOT NULL,
    "RequiresConfirmation" boolean DEFAULT false NOT NULL,
    "IsConfirmed" boolean DEFAULT false NOT NULL,
    "ConfirmedAt" timestamp with time zone,
    "ConfirmedBy" character varying(50),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean DEFAULT false NOT NULL,
    "CreatedById" character varying(500) NOT NULL,
    "UpdatedById" character varying(500)
);


--
-- Name: GroupMembers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."GroupMembers" (
    "GroupId" uuid NOT NULL,
    "DeviceId" uuid NOT NULL,
    "GroupId1" uuid NOT NULL,
    "DeviceId1" uuid NOT NULL,
    "Id" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: GroupStateHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."GroupStateHistory" (
    "Id" uuid NOT NULL,
    "GroupId" uuid NOT NULL,
    "GroupId1" uuid NOT NULL,
    "OldState" jsonb NOT NULL,
    "NewState" jsonb NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: GroupStates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."GroupStates" (
    "GroupId" uuid NOT NULL,
    "State" jsonb NOT NULL,
    "LastUpdated" timestamp with time zone NOT NULL,
    "Id" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: Groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Groups" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: Notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Notifications" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "Message" text NOT NULL,
    "Type" integer NOT NULL,
    "Severity" integer,
    "IsRead" boolean NOT NULL,
    "ReadAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: Rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Rooms" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Floor" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: RuleActions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RuleActions" (
    "Id" uuid NOT NULL,
    "RuleId" uuid NOT NULL,
    "RuleId1" uuid NOT NULL,
    "Action" jsonb NOT NULL,
    "Order" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: RuleConditions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RuleConditions" (
    "Id" uuid NOT NULL,
    "RuleId" uuid NOT NULL,
    "RuleId1" uuid NOT NULL,
    "Condition" jsonb NOT NULL,
    "Order" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: RuleExecutionHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RuleExecutionHistory" (
    "Id" uuid NOT NULL,
    "RuleId" uuid NOT NULL,
    "RuleId1" uuid NOT NULL,
    "Success" boolean NOT NULL,
    "Result" jsonb,
    "ErrorMessage" text,
    "ExecutionTime" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: RuleTriggers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."RuleTriggers" (
    "Id" uuid NOT NULL,
    "RuleId" uuid NOT NULL,
    "TriggerType" text NOT NULL,
    "Trigger" jsonb NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "LastTriggered" timestamp with time zone,
    "RuleId1" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: Rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Rules" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "Condition" jsonb NOT NULL,
    "Action" jsonb NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: UserDevicePermissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."UserDevicePermissions" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "DeviceId" uuid NOT NULL,
    "PermissionLevel" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: UserRoomPermissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."UserRoomPermissions" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "RoomId" uuid NOT NULL,
    "Permission" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: UserSettings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."UserSettings" (
    "UserId" text NOT NULL,
    "Theme" text NOT NULL,
    "Language" text NOT NULL,
    "ShowOfflineDevices" boolean NOT NULL,
    "DefaultView" text NOT NULL,
    "DashboardLayout" jsonb,
    "FavoriteDevices" jsonb,
    "QuickActions" jsonb,
    "EmailNotifications" boolean NOT NULL,
    "PushNotifications" boolean NOT NULL,
    "NotificationPreferences" jsonb,
    "DeviceDisplayPreferences" jsonb,
    "LastUsedDevices" jsonb,
    "RoomDisplayOrder" jsonb,
    "ShowEmptyRooms" boolean NOT NULL,
    "ShowAutomationSuggestions" boolean NOT NULL,
    "AutomationPreferences" jsonb,
    "UserId1" text NOT NULL,
    "Id" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" text NOT NULL,
    "UpdatedById" text
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: ApplicationUsers PK_ApplicationUsers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ApplicationUsers"
    ADD CONSTRAINT "PK_ApplicationUsers" PRIMARY KEY ("Id");


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Clusters PK_Clusters; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Clusters"
    ADD CONSTRAINT "PK_Clusters" PRIMARY KEY ("Id");


--
-- Name: DeviceDeviceGroup PK_DeviceDeviceGroup; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceDeviceGroup"
    ADD CONSTRAINT "PK_DeviceDeviceGroup" PRIMARY KEY ("DeviceGroupsId", "DevicesId");


--
-- Name: DeviceEvents PK_DeviceEvents; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceEvents"
    ADD CONSTRAINT "PK_DeviceEvents" PRIMARY KEY ("Id");


--
-- Name: DeviceFirmwareUpdates PK_DeviceFirmwareUpdates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceFirmwareUpdates"
    ADD CONSTRAINT "PK_DeviceFirmwareUpdates" PRIMARY KEY ("Id");


--
-- Name: DeviceGroupMembers PK_DeviceGroupMembers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceGroupMembers"
    ADD CONSTRAINT "PK_DeviceGroupMembers" PRIMARY KEY ("DeviceId", "DeviceGroupId");


--
-- Name: DeviceGroups PK_DeviceGroups; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceGroups"
    ADD CONSTRAINT "PK_DeviceGroups" PRIMARY KEY ("Id");


--
-- Name: DeviceHistory PK_DeviceHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceHistory"
    ADD CONSTRAINT "PK_DeviceHistory" PRIMARY KEY ("Id");


--
-- Name: DevicePropertyChanges PK_DevicePropertyChanges; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DevicePropertyChanges"
    ADD CONSTRAINT "PK_DevicePropertyChanges" PRIMARY KEY ("Id");


--
-- Name: DeviceStates PK_DeviceStates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceStates"
    ADD CONSTRAINT "PK_DeviceStates" PRIMARY KEY ("Id");


--
-- Name: DeviceTypes PK_DeviceTypes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceTypes"
    ADD CONSTRAINT "PK_DeviceTypes" PRIMARY KEY ("Id");


--
-- Name: Devices PK_Devices; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Devices"
    ADD CONSTRAINT "PK_Devices" PRIMARY KEY ("Id");


--
-- Name: EnvironmentalSettings PK_EnvironmentalSettings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."EnvironmentalSettings"
    ADD CONSTRAINT "PK_EnvironmentalSettings" PRIMARY KEY ("Id");


--
-- Name: FirmwareUpdates PK_FirmwareUpdates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FirmwareUpdates"
    ADD CONSTRAINT "PK_FirmwareUpdates" PRIMARY KEY ("Id");


--
-- Name: GroupMembers PK_GroupMembers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupMembers"
    ADD CONSTRAINT "PK_GroupMembers" PRIMARY KEY ("GroupId", "DeviceId");


--
-- Name: GroupStateHistory PK_GroupStateHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupStateHistory"
    ADD CONSTRAINT "PK_GroupStateHistory" PRIMARY KEY ("Id");


--
-- Name: GroupStates PK_GroupStates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupStates"
    ADD CONSTRAINT "PK_GroupStates" PRIMARY KEY ("GroupId");


--
-- Name: Groups PK_Groups; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Groups"
    ADD CONSTRAINT "PK_Groups" PRIMARY KEY ("Id");


--
-- Name: Notifications PK_Notifications; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id");


--
-- Name: Rooms PK_Rooms; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rooms"
    ADD CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id");


--
-- Name: RuleActions PK_RuleActions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleActions"
    ADD CONSTRAINT "PK_RuleActions" PRIMARY KEY ("Id");


--
-- Name: RuleConditions PK_RuleConditions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleConditions"
    ADD CONSTRAINT "PK_RuleConditions" PRIMARY KEY ("Id");


--
-- Name: RuleExecutionHistory PK_RuleExecutionHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleExecutionHistory"
    ADD CONSTRAINT "PK_RuleExecutionHistory" PRIMARY KEY ("Id");


--
-- Name: RuleTriggers PK_RuleTriggers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleTriggers"
    ADD CONSTRAINT "PK_RuleTriggers" PRIMARY KEY ("Id");


--
-- Name: Rules PK_Rules; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rules"
    ADD CONSTRAINT "PK_Rules" PRIMARY KEY ("Id");


--
-- Name: UserDevicePermissions PK_UserDevicePermissions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserDevicePermissions"
    ADD CONSTRAINT "PK_UserDevicePermissions" PRIMARY KEY ("Id");


--
-- Name: UserRoomPermissions PK_UserRoomPermissions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserRoomPermissions"
    ADD CONSTRAINT "PK_UserRoomPermissions" PRIMARY KEY ("Id");


--
-- Name: UserSettings PK_UserSettings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserSettings"
    ADD CONSTRAINT "PK_UserSettings" PRIMARY KEY ("UserId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_ApplicationUsers_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ApplicationUsers_CreatedById" ON public."ApplicationUsers" USING btree ("CreatedById");


--
-- Name: IX_ApplicationUsers_Email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ApplicationUsers_Email" ON public."ApplicationUsers" USING btree ("Email");


--
-- Name: IX_ApplicationUsers_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ApplicationUsers_UpdatedById" ON public."ApplicationUsers" USING btree ("UpdatedById");


--
-- Name: IX_ApplicationUsers_UserName; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ApplicationUsers_UserName" ON public."ApplicationUsers" USING btree ("UserName");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_Clusters_ClusterId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Clusters_ClusterId" ON public."Clusters" USING btree ("ClusterId");


--
-- Name: IX_Clusters_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Clusters_CreatedById" ON public."Clusters" USING btree ("CreatedById");


--
-- Name: IX_Clusters_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Clusters_UpdatedById" ON public."Clusters" USING btree ("UpdatedById");


--
-- Name: IX_DeviceDeviceGroup_DevicesId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceDeviceGroup_DevicesId" ON public."DeviceDeviceGroup" USING btree ("DevicesId");


--
-- Name: IX_DeviceEvents_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceEvents_CreatedById" ON public."DeviceEvents" USING btree ("CreatedById");


--
-- Name: IX_DeviceEvents_DeviceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceEvents_DeviceId" ON public."DeviceEvents" USING btree ("DeviceId");


--
-- Name: IX_DeviceEvents_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceEvents_UpdatedById" ON public."DeviceEvents" USING btree ("UpdatedById");


--
-- Name: IX_DeviceFirmwareUpdates_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceFirmwareUpdates_CreatedById" ON public."DeviceFirmwareUpdates" USING btree ("CreatedById");


--
-- Name: IX_DeviceFirmwareUpdates_DeviceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceFirmwareUpdates_DeviceId" ON public."DeviceFirmwareUpdates" USING btree ("DeviceId");


--
-- Name: IX_DeviceFirmwareUpdates_FirmwareUpdateId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceFirmwareUpdates_FirmwareUpdateId" ON public."DeviceFirmwareUpdates" USING btree ("FirmwareUpdateId");


--
-- Name: IX_DeviceFirmwareUpdates_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceFirmwareUpdates_UpdatedById" ON public."DeviceFirmwareUpdates" USING btree ("UpdatedById");


--
-- Name: IX_DeviceGroupMembers_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceGroupMembers_CreatedById" ON public."DeviceGroupMembers" USING btree ("CreatedById");


--
-- Name: IX_DeviceGroupMembers_DeviceGroupId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceGroupMembers_DeviceGroupId" ON public."DeviceGroupMembers" USING btree ("DeviceGroupId");


--
-- Name: IX_DeviceGroupMembers_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceGroupMembers_UpdatedById" ON public."DeviceGroupMembers" USING btree ("UpdatedById");


--
-- Name: IX_DeviceGroups_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceGroups_CreatedById" ON public."DeviceGroups" USING btree ("CreatedById");


--
-- Name: IX_DeviceGroups_RoomId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceGroups_RoomId" ON public."DeviceGroups" USING btree ("RoomId");


--
-- Name: IX_DeviceGroups_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceGroups_UpdatedById" ON public."DeviceGroups" USING btree ("UpdatedById");


--
-- Name: IX_DeviceHistory_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceHistory_CreatedById" ON public."DeviceHistory" USING btree ("CreatedById");


--
-- Name: IX_DeviceHistory_DeviceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceHistory_DeviceId" ON public."DeviceHistory" USING btree ("DeviceId");


--
-- Name: IX_DeviceHistory_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceHistory_UpdatedById" ON public."DeviceHistory" USING btree ("UpdatedById");


--
-- Name: IX_DevicePropertyChanges_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DevicePropertyChanges_CreatedById" ON public."DevicePropertyChanges" USING btree ("CreatedById");


--
-- Name: IX_DevicePropertyChanges_DeviceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DevicePropertyChanges_DeviceId" ON public."DevicePropertyChanges" USING btree ("DeviceId");


--
-- Name: IX_DevicePropertyChanges_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DevicePropertyChanges_UpdatedById" ON public."DevicePropertyChanges" USING btree ("UpdatedById");


--
-- Name: IX_DeviceStates_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceStates_CreatedById" ON public."DeviceStates" USING btree ("CreatedById");


--
-- Name: IX_DeviceStates_DeviceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceStates_DeviceId" ON public."DeviceStates" USING btree ("DeviceId");


--
-- Name: IX_DeviceStates_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceStates_UpdatedById" ON public."DeviceStates" USING btree ("UpdatedById");


--
-- Name: IX_DeviceTypes_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceTypes_CreatedById" ON public."DeviceTypes" USING btree ("CreatedById");


--
-- Name: IX_DeviceTypes_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_DeviceTypes_UpdatedById" ON public."DeviceTypes" USING btree ("UpdatedById");


--
-- Name: IX_Devices_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Devices_CreatedById" ON public."Devices" USING btree ("CreatedById");


--
-- Name: IX_Devices_DeviceTypeId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Devices_DeviceTypeId" ON public."Devices" USING btree ("DeviceTypeId");


--
-- Name: IX_Devices_MatterDeviceId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Devices_MatterDeviceId" ON public."Devices" USING btree ("MatterDeviceId") WHERE ("MatterDeviceId" IS NOT NULL);


--
-- Name: IX_Devices_RoomId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Devices_RoomId" ON public."Devices" USING btree ("RoomId");


--
-- Name: IX_Devices_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Devices_UpdatedById" ON public."Devices" USING btree ("UpdatedById");


--
-- Name: IX_EnvironmentalSettings_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_EnvironmentalSettings_CreatedById" ON public."EnvironmentalSettings" USING btree ("CreatedById");


--
-- Name: IX_EnvironmentalSettings_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_EnvironmentalSettings_UpdatedById" ON public."EnvironmentalSettings" USING btree ("UpdatedById");


--
-- Name: IX_EnvironmentalSettings_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_EnvironmentalSettings_UserId" ON public."EnvironmentalSettings" USING btree ("UserId");


--
-- Name: IX_FirmwareUpdates_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_FirmwareUpdates_CreatedById" ON public."FirmwareUpdates" USING btree ("CreatedById");


--
-- Name: IX_FirmwareUpdates_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_FirmwareUpdates_UpdatedById" ON public."FirmwareUpdates" USING btree ("UpdatedById");


--
-- Name: IX_GroupMembers_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GroupMembers_CreatedById" ON public."GroupMembers" USING btree ("CreatedById");


--
-- Name: IX_GroupMembers_DeviceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GroupMembers_DeviceId" ON public."GroupMembers" USING btree ("DeviceId");


--
-- Name: IX_GroupMembers_DeviceId1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GroupMembers_DeviceId1" ON public."GroupMembers" USING btree ("DeviceId1");


--
-- Name: IX_GroupMembers_GroupId1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GroupMembers_GroupId1" ON public."GroupMembers" USING btree ("GroupId1");


--
-- Name: IX_GroupMembers_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GroupMembers_UpdatedById" ON public."GroupMembers" USING btree ("UpdatedById");


--
-- Name: IX_GroupStateHistory_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GroupStateHistory_CreatedById" ON public."GroupStateHistory" USING btree ("CreatedById");


--
-- Name: IX_GroupStateHistory_GroupId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GroupStateHistory_GroupId" ON public."GroupStateHistory" USING btree ("GroupId");


--
-- Name: IX_GroupStateHistory_GroupId1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GroupStateHistory_GroupId1" ON public."GroupStateHistory" USING btree ("GroupId1");


--
-- Name: IX_GroupStateHistory_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GroupStateHistory_UpdatedById" ON public."GroupStateHistory" USING btree ("UpdatedById");


--
-- Name: IX_GroupStates_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GroupStates_CreatedById" ON public."GroupStates" USING btree ("CreatedById");


--
-- Name: IX_GroupStates_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_GroupStates_UpdatedById" ON public."GroupStates" USING btree ("UpdatedById");


--
-- Name: IX_Groups_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Groups_CreatedById" ON public."Groups" USING btree ("CreatedById");


--
-- Name: IX_Groups_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Groups_UpdatedById" ON public."Groups" USING btree ("UpdatedById");


--
-- Name: IX_Notifications_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Notifications_CreatedById" ON public."Notifications" USING btree ("CreatedById");


--
-- Name: IX_Notifications_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Notifications_UpdatedById" ON public."Notifications" USING btree ("UpdatedById");


--
-- Name: IX_Rooms_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Rooms_CreatedById" ON public."Rooms" USING btree ("CreatedById");


--
-- Name: IX_Rooms_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Rooms_UpdatedById" ON public."Rooms" USING btree ("UpdatedById");


--
-- Name: IX_RuleActions_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleActions_CreatedById" ON public."RuleActions" USING btree ("CreatedById");


--
-- Name: IX_RuleActions_RuleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleActions_RuleId" ON public."RuleActions" USING btree ("RuleId");


--
-- Name: IX_RuleActions_RuleId1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleActions_RuleId1" ON public."RuleActions" USING btree ("RuleId1");


--
-- Name: IX_RuleActions_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleActions_UpdatedById" ON public."RuleActions" USING btree ("UpdatedById");


--
-- Name: IX_RuleConditions_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleConditions_CreatedById" ON public."RuleConditions" USING btree ("CreatedById");


--
-- Name: IX_RuleConditions_RuleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleConditions_RuleId" ON public."RuleConditions" USING btree ("RuleId");


--
-- Name: IX_RuleConditions_RuleId1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleConditions_RuleId1" ON public."RuleConditions" USING btree ("RuleId1");


--
-- Name: IX_RuleConditions_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleConditions_UpdatedById" ON public."RuleConditions" USING btree ("UpdatedById");


--
-- Name: IX_RuleExecutionHistory_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleExecutionHistory_CreatedById" ON public."RuleExecutionHistory" USING btree ("CreatedById");


--
-- Name: IX_RuleExecutionHistory_RuleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleExecutionHistory_RuleId" ON public."RuleExecutionHistory" USING btree ("RuleId");


--
-- Name: IX_RuleExecutionHistory_RuleId1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleExecutionHistory_RuleId1" ON public."RuleExecutionHistory" USING btree ("RuleId1");


--
-- Name: IX_RuleExecutionHistory_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleExecutionHistory_UpdatedById" ON public."RuleExecutionHistory" USING btree ("UpdatedById");


--
-- Name: IX_RuleTriggers_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleTriggers_CreatedById" ON public."RuleTriggers" USING btree ("CreatedById");


--
-- Name: IX_RuleTriggers_RuleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleTriggers_RuleId" ON public."RuleTriggers" USING btree ("RuleId");


--
-- Name: IX_RuleTriggers_RuleId1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleTriggers_RuleId1" ON public."RuleTriggers" USING btree ("RuleId1");


--
-- Name: IX_RuleTriggers_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_RuleTriggers_UpdatedById" ON public."RuleTriggers" USING btree ("UpdatedById");


--
-- Name: IX_Rules_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Rules_CreatedById" ON public."Rules" USING btree ("CreatedById");


--
-- Name: IX_Rules_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Rules_UpdatedById" ON public."Rules" USING btree ("UpdatedById");


--
-- Name: IX_UserDevicePermissions_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserDevicePermissions_CreatedById" ON public."UserDevicePermissions" USING btree ("CreatedById");


--
-- Name: IX_UserDevicePermissions_DeviceId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserDevicePermissions_DeviceId" ON public."UserDevicePermissions" USING btree ("DeviceId");


--
-- Name: IX_UserDevicePermissions_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserDevicePermissions_UpdatedById" ON public."UserDevicePermissions" USING btree ("UpdatedById");


--
-- Name: IX_UserDevicePermissions_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserDevicePermissions_UserId" ON public."UserDevicePermissions" USING btree ("UserId");


--
-- Name: IX_UserRoomPermissions_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserRoomPermissions_CreatedById" ON public."UserRoomPermissions" USING btree ("CreatedById");


--
-- Name: IX_UserRoomPermissions_RoomId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserRoomPermissions_RoomId" ON public."UserRoomPermissions" USING btree ("RoomId");


--
-- Name: IX_UserRoomPermissions_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserRoomPermissions_UpdatedById" ON public."UserRoomPermissions" USING btree ("UpdatedById");


--
-- Name: IX_UserRoomPermissions_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserRoomPermissions_UserId" ON public."UserRoomPermissions" USING btree ("UserId");


--
-- Name: IX_UserSettings_CreatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserSettings_CreatedById" ON public."UserSettings" USING btree ("CreatedById");


--
-- Name: IX_UserSettings_UpdatedById; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserSettings_UpdatedById" ON public."UserSettings" USING btree ("UpdatedById");


--
-- Name: IX_UserSettings_UserId1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserSettings_UserId1" ON public."UserSettings" USING btree ("UserId1");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: ApplicationUsers FK_ApplicationUsers_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ApplicationUsers"
    ADD CONSTRAINT "FK_ApplicationUsers_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: ApplicationUsers FK_ApplicationUsers_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ApplicationUsers"
    ADD CONSTRAINT "FK_ApplicationUsers_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Clusters FK_Clusters_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Clusters"
    ADD CONSTRAINT "FK_Clusters_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Clusters FK_Clusters_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Clusters"
    ADD CONSTRAINT "FK_Clusters_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceDeviceGroup FK_DeviceDeviceGroup_DeviceGroups_DeviceGroupsId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceDeviceGroup"
    ADD CONSTRAINT "FK_DeviceDeviceGroup_DeviceGroups_DeviceGroupsId" FOREIGN KEY ("DeviceGroupsId") REFERENCES public."DeviceGroups"("Id") ON DELETE CASCADE;


--
-- Name: DeviceDeviceGroup FK_DeviceDeviceGroup_Devices_DevicesId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceDeviceGroup"
    ADD CONSTRAINT "FK_DeviceDeviceGroup_Devices_DevicesId" FOREIGN KEY ("DevicesId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- Name: DeviceEvents FK_DeviceEvents_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceEvents"
    ADD CONSTRAINT "FK_DeviceEvents_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceEvents FK_DeviceEvents_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceEvents"
    ADD CONSTRAINT "FK_DeviceEvents_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceEvents FK_DeviceEvents_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceEvents"
    ADD CONSTRAINT "FK_DeviceEvents_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- Name: DeviceFirmwareUpdates FK_DeviceFirmwareUpdates_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceFirmwareUpdates"
    ADD CONSTRAINT "FK_DeviceFirmwareUpdates_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceFirmwareUpdates FK_DeviceFirmwareUpdates_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceFirmwareUpdates"
    ADD CONSTRAINT "FK_DeviceFirmwareUpdates_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceFirmwareUpdates FK_DeviceFirmwareUpdates_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceFirmwareUpdates"
    ADD CONSTRAINT "FK_DeviceFirmwareUpdates_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- Name: DeviceFirmwareUpdates FK_DeviceFirmwareUpdates_FirmwareUpdates_FirmwareUpdateId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceFirmwareUpdates"
    ADD CONSTRAINT "FK_DeviceFirmwareUpdates_FirmwareUpdates_FirmwareUpdateId" FOREIGN KEY ("FirmwareUpdateId") REFERENCES public."FirmwareUpdates"("Id") ON DELETE CASCADE;


--
-- Name: DeviceGroupMembers FK_DeviceGroupMembers_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceGroupMembers"
    ADD CONSTRAINT "FK_DeviceGroupMembers_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE CASCADE;


--
-- Name: DeviceGroupMembers FK_DeviceGroupMembers_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceGroupMembers"
    ADD CONSTRAINT "FK_DeviceGroupMembers_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id");


--
-- Name: DeviceGroupMembers FK_DeviceGroupMembers_DeviceGroups_DeviceGroupId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceGroupMembers"
    ADD CONSTRAINT "FK_DeviceGroupMembers_DeviceGroups_DeviceGroupId" FOREIGN KEY ("DeviceGroupId") REFERENCES public."DeviceGroups"("Id") ON DELETE CASCADE;


--
-- Name: DeviceGroupMembers FK_DeviceGroupMembers_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceGroupMembers"
    ADD CONSTRAINT "FK_DeviceGroupMembers_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- Name: DeviceGroups FK_DeviceGroups_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceGroups"
    ADD CONSTRAINT "FK_DeviceGroups_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceGroups FK_DeviceGroups_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceGroups"
    ADD CONSTRAINT "FK_DeviceGroups_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceGroups FK_DeviceGroups_Rooms_RoomId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceGroups"
    ADD CONSTRAINT "FK_DeviceGroups_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES public."Rooms"("Id");


--
-- Name: DeviceHistory FK_DeviceHistory_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceHistory"
    ADD CONSTRAINT "FK_DeviceHistory_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceHistory FK_DeviceHistory_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceHistory"
    ADD CONSTRAINT "FK_DeviceHistory_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceHistory FK_DeviceHistory_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceHistory"
    ADD CONSTRAINT "FK_DeviceHistory_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- Name: DevicePropertyChanges FK_DevicePropertyChanges_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DevicePropertyChanges"
    ADD CONSTRAINT "FK_DevicePropertyChanges_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DevicePropertyChanges FK_DevicePropertyChanges_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DevicePropertyChanges"
    ADD CONSTRAINT "FK_DevicePropertyChanges_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DevicePropertyChanges FK_DevicePropertyChanges_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DevicePropertyChanges"
    ADD CONSTRAINT "FK_DevicePropertyChanges_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- Name: DeviceStates FK_DeviceStates_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceStates"
    ADD CONSTRAINT "FK_DeviceStates_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceStates FK_DeviceStates_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceStates"
    ADD CONSTRAINT "FK_DeviceStates_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceStates FK_DeviceStates_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceStates"
    ADD CONSTRAINT "FK_DeviceStates_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- Name: DeviceTypes FK_DeviceTypes_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceTypes"
    ADD CONSTRAINT "FK_DeviceTypes_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceTypes FK_DeviceTypes_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceTypes"
    ADD CONSTRAINT "FK_DeviceTypes_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: DeviceTypes FK_DeviceTypes_DeviceGroups_DeviceGroupId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."DeviceTypes"
    ADD CONSTRAINT "FK_DeviceTypes_DeviceGroups_DeviceGroupId" FOREIGN KEY ("DeviceGroupId") REFERENCES public."DeviceGroups"("Id") ON DELETE RESTRICT;


--
-- Name: Devices FK_Devices_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Devices"
    ADD CONSTRAINT "FK_Devices_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Devices FK_Devices_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Devices"
    ADD CONSTRAINT "FK_Devices_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Devices FK_Devices_DeviceTypes_DeviceTypeId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Devices"
    ADD CONSTRAINT "FK_Devices_DeviceTypes_DeviceTypeId" FOREIGN KEY ("DeviceTypeId") REFERENCES public."DeviceTypes"("Id") ON DELETE RESTRICT;


--
-- Name: Devices FK_Devices_Rooms_RoomId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Devices"
    ADD CONSTRAINT "FK_Devices_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES public."Rooms"("Id") ON DELETE RESTRICT;


--
-- Name: EnvironmentalSettings FK_EnvironmentalSettings_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."EnvironmentalSettings"
    ADD CONSTRAINT "FK_EnvironmentalSettings_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: EnvironmentalSettings FK_EnvironmentalSettings_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."EnvironmentalSettings"
    ADD CONSTRAINT "FK_EnvironmentalSettings_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: EnvironmentalSettings FK_EnvironmentalSettings_ApplicationUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."EnvironmentalSettings"
    ADD CONSTRAINT "FK_EnvironmentalSettings_ApplicationUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."ApplicationUsers"("Id") ON DELETE CASCADE;


--
-- Name: FirmwareUpdates FK_FirmwareUpdates_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FirmwareUpdates"
    ADD CONSTRAINT "FK_FirmwareUpdates_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: FirmwareUpdates FK_FirmwareUpdates_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FirmwareUpdates"
    ADD CONSTRAINT "FK_FirmwareUpdates_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: GroupMembers FK_GroupMembers_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupMembers"
    ADD CONSTRAINT "FK_GroupMembers_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: GroupMembers FK_GroupMembers_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupMembers"
    ADD CONSTRAINT "FK_GroupMembers_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: GroupMembers FK_GroupMembers_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupMembers"
    ADD CONSTRAINT "FK_GroupMembers_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- Name: GroupMembers FK_GroupMembers_Devices_DeviceId1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupMembers"
    ADD CONSTRAINT "FK_GroupMembers_Devices_DeviceId1" FOREIGN KEY ("DeviceId1") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- Name: GroupMembers FK_GroupMembers_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupMembers"
    ADD CONSTRAINT "FK_GroupMembers_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("Id") ON DELETE CASCADE;


--
-- Name: GroupMembers FK_GroupMembers_Groups_GroupId1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupMembers"
    ADD CONSTRAINT "FK_GroupMembers_Groups_GroupId1" FOREIGN KEY ("GroupId1") REFERENCES public."Groups"("Id") ON DELETE CASCADE;


--
-- Name: GroupStateHistory FK_GroupStateHistory_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupStateHistory"
    ADD CONSTRAINT "FK_GroupStateHistory_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: GroupStateHistory FK_GroupStateHistory_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupStateHistory"
    ADD CONSTRAINT "FK_GroupStateHistory_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: GroupStateHistory FK_GroupStateHistory_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupStateHistory"
    ADD CONSTRAINT "FK_GroupStateHistory_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("Id") ON DELETE CASCADE;


--
-- Name: GroupStateHistory FK_GroupStateHistory_Groups_GroupId1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupStateHistory"
    ADD CONSTRAINT "FK_GroupStateHistory_Groups_GroupId1" FOREIGN KEY ("GroupId1") REFERENCES public."Groups"("Id") ON DELETE CASCADE;


--
-- Name: GroupStates FK_GroupStates_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupStates"
    ADD CONSTRAINT "FK_GroupStates_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: GroupStates FK_GroupStates_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupStates"
    ADD CONSTRAINT "FK_GroupStates_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: GroupStates FK_GroupStates_Groups_GroupId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."GroupStates"
    ADD CONSTRAINT "FK_GroupStates_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES public."Groups"("Id") ON DELETE CASCADE;


--
-- Name: Groups FK_Groups_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Groups"
    ADD CONSTRAINT "FK_Groups_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Groups FK_Groups_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Groups"
    ADD CONSTRAINT "FK_Groups_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Notifications FK_Notifications_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "FK_Notifications_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Notifications FK_Notifications_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "FK_Notifications_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Rooms FK_Rooms_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rooms"
    ADD CONSTRAINT "FK_Rooms_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Rooms FK_Rooms_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rooms"
    ADD CONSTRAINT "FK_Rooms_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: RuleActions FK_RuleActions_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleActions"
    ADD CONSTRAINT "FK_RuleActions_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: RuleActions FK_RuleActions_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleActions"
    ADD CONSTRAINT "FK_RuleActions_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: RuleActions FK_RuleActions_Rules_RuleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleActions"
    ADD CONSTRAINT "FK_RuleActions_Rules_RuleId" FOREIGN KEY ("RuleId") REFERENCES public."Rules"("Id") ON DELETE CASCADE;


--
-- Name: RuleActions FK_RuleActions_Rules_RuleId1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleActions"
    ADD CONSTRAINT "FK_RuleActions_Rules_RuleId1" FOREIGN KEY ("RuleId1") REFERENCES public."Rules"("Id") ON DELETE CASCADE;


--
-- Name: RuleConditions FK_RuleConditions_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleConditions"
    ADD CONSTRAINT "FK_RuleConditions_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: RuleConditions FK_RuleConditions_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleConditions"
    ADD CONSTRAINT "FK_RuleConditions_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: RuleConditions FK_RuleConditions_Rules_RuleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleConditions"
    ADD CONSTRAINT "FK_RuleConditions_Rules_RuleId" FOREIGN KEY ("RuleId") REFERENCES public."Rules"("Id") ON DELETE CASCADE;


--
-- Name: RuleConditions FK_RuleConditions_Rules_RuleId1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleConditions"
    ADD CONSTRAINT "FK_RuleConditions_Rules_RuleId1" FOREIGN KEY ("RuleId1") REFERENCES public."Rules"("Id") ON DELETE CASCADE;


--
-- Name: RuleExecutionHistory FK_RuleExecutionHistory_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleExecutionHistory"
    ADD CONSTRAINT "FK_RuleExecutionHistory_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: RuleExecutionHistory FK_RuleExecutionHistory_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleExecutionHistory"
    ADD CONSTRAINT "FK_RuleExecutionHistory_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: RuleExecutionHistory FK_RuleExecutionHistory_Rules_RuleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleExecutionHistory"
    ADD CONSTRAINT "FK_RuleExecutionHistory_Rules_RuleId" FOREIGN KEY ("RuleId") REFERENCES public."Rules"("Id") ON DELETE CASCADE;


--
-- Name: RuleExecutionHistory FK_RuleExecutionHistory_Rules_RuleId1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleExecutionHistory"
    ADD CONSTRAINT "FK_RuleExecutionHistory_Rules_RuleId1" FOREIGN KEY ("RuleId1") REFERENCES public."Rules"("Id") ON DELETE CASCADE;


--
-- Name: RuleTriggers FK_RuleTriggers_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleTriggers"
    ADD CONSTRAINT "FK_RuleTriggers_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: RuleTriggers FK_RuleTriggers_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleTriggers"
    ADD CONSTRAINT "FK_RuleTriggers_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: RuleTriggers FK_RuleTriggers_Rules_RuleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleTriggers"
    ADD CONSTRAINT "FK_RuleTriggers_Rules_RuleId" FOREIGN KEY ("RuleId") REFERENCES public."Rules"("Id") ON DELETE CASCADE;


--
-- Name: RuleTriggers FK_RuleTriggers_Rules_RuleId1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."RuleTriggers"
    ADD CONSTRAINT "FK_RuleTriggers_Rules_RuleId1" FOREIGN KEY ("RuleId1") REFERENCES public."Rules"("Id") ON DELETE CASCADE;


--
-- Name: Rules FK_Rules_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rules"
    ADD CONSTRAINT "FK_Rules_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Rules FK_Rules_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Rules"
    ADD CONSTRAINT "FK_Rules_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: UserDevicePermissions FK_UserDevicePermissions_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserDevicePermissions"
    ADD CONSTRAINT "FK_UserDevicePermissions_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: UserDevicePermissions FK_UserDevicePermissions_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserDevicePermissions"
    ADD CONSTRAINT "FK_UserDevicePermissions_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: UserDevicePermissions FK_UserDevicePermissions_ApplicationUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserDevicePermissions"
    ADD CONSTRAINT "FK_UserDevicePermissions_ApplicationUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."ApplicationUsers"("Id") ON DELETE CASCADE;


--
-- Name: UserDevicePermissions FK_UserDevicePermissions_Devices_DeviceId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserDevicePermissions"
    ADD CONSTRAINT "FK_UserDevicePermissions_Devices_DeviceId" FOREIGN KEY ("DeviceId") REFERENCES public."Devices"("Id") ON DELETE CASCADE;


--
-- Name: UserRoomPermissions FK_UserRoomPermissions_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserRoomPermissions"
    ADD CONSTRAINT "FK_UserRoomPermissions_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: UserRoomPermissions FK_UserRoomPermissions_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserRoomPermissions"
    ADD CONSTRAINT "FK_UserRoomPermissions_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: UserRoomPermissions FK_UserRoomPermissions_ApplicationUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserRoomPermissions"
    ADD CONSTRAINT "FK_UserRoomPermissions_ApplicationUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."ApplicationUsers"("Id") ON DELETE CASCADE;


--
-- Name: UserRoomPermissions FK_UserRoomPermissions_Rooms_RoomId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserRoomPermissions"
    ADD CONSTRAINT "FK_UserRoomPermissions_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES public."Rooms"("Id") ON DELETE CASCADE;


--
-- Name: UserSettings FK_UserSettings_ApplicationUsers_CreatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserSettings"
    ADD CONSTRAINT "FK_UserSettings_ApplicationUsers_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: UserSettings FK_UserSettings_ApplicationUsers_UpdatedById; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserSettings"
    ADD CONSTRAINT "FK_UserSettings_ApplicationUsers_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES public."ApplicationUsers"("Id") ON DELETE RESTRICT;


--
-- Name: UserSettings FK_UserSettings_ApplicationUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserSettings"
    ADD CONSTRAINT "FK_UserSettings_ApplicationUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."ApplicationUsers"("Id") ON DELETE CASCADE;


--
-- Name: UserSettings FK_UserSettings_ApplicationUsers_UserId1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserSettings"
    ADD CONSTRAINT "FK_UserSettings_ApplicationUsers_UserId1" FOREIGN KEY ("UserId1") REFERENCES public."ApplicationUsers"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

