version: '3.8'

services:
  bluetooth-test:
    build: .
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/vchiq:/dev/vchiq  # For Raspberry Pi Bluetooth
    volumes:
      - /var/run/bluetooth:/var/run/bluetooth
      - /sys/class/bluetooth:/sys/class/bluetooth
      - /etc/bluetooth:/etc/bluetooth:ro
      - /var/lib/bluetooth:/var/lib/bluetooth:ro
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_BROADCAST
      - SYS_RAWIO
      - SYS_NICE
      - BLOCK_SUSPEND
    security_opt:
      - seccomp:unconfined
    network_mode: host 